In [11]:
import pandas as pd
data = pd.read_table('stores_location.dat', delim_whitespace=True, names = ('store', 'city', 'longitude', 'N', 'latitude','W'))
data

store          city  longitude  N  latitude  W
0  store#1   Tallahassee    30.4550  N   84.2533  W
1  store#2   Gainesville    29.6520  N   82.3250  W
2  store#3         Miami    25.7753  N   80.2089  W
3  store#4  Jacksonville    30.3369  N   81.6614  W
4  store#5         Tampa    27.9681  N   82.4764  W
5  store#6       Orlando    28.4158  N   81.2989  W
6  store#7       Hialeah    25.8606  N   80.2939  W

In [58]:
import numpy as np 

def selectionSearch(A):
    #use numpy argsort to return indicies that would sort the array 
    indx = np.argsort(A)
    #Traverse through numpy array 
    for i in range(len(A)):
        #initial minimum location 
        min_loc = i
        #find location of smallest element on right 
        for j in range(i + 1, len(A)):
            #Check if number to the right is smaller then minimum location
            if A[j] < A[min_loc]:
                min_loc = j
        #Within the first for loop swap the minimum location with first element 
        A[min_loc], A[i] = A[i], A[min_loc]
    
    return A, indx

In [64]:
A = np.random.rand(25) * 100
selectionSearch(A)

(array([ 0.90721523, 16.54928166, 25.52236388, 26.60734164, 29.00118971,
        31.88875098, 36.30040202, 36.88660358, 53.42127779, 55.36322847,
        55.68976494, 60.26986475, 67.50090213, 71.5043357 , 72.4968277 ,
        74.38201469, 75.45784003, 76.13983337, 76.22507462, 84.35775607,
        91.32904795, 91.3700662 , 91.58054875, 96.61009071, 98.93875448]),
 array([10, 21,  5, 17,  4,  3,  2, 20, 14, 11, 13, 24, 16,  6,  0,  8,  7,
        22, 18, 19,  1, 12,  9, 23, 15], dtype=int32))

In [92]:
def bubbleSort(A):
    #Traverse the numpy array
    #Use length minus 1 since we are comparing the current value with the next 
    for i in range(len(A) - 1):
        #At each sweep compare the current j with the next value 
        for j in range((len(A) - 1) - i):
            #Swap positions if left values are larger than right to move large numbers to the back 
            if A[j] > A[j + 1]:
                A[j], A[j + 1] = A[j + 1], A[j]
    return A

In [93]:
A = np.random.rand(25) * 100
bubbleSort(A)

array([ 0.25238487, 13.64547363, 16.67375204, 17.67899187, 18.14187173,
       19.19779346, 19.75387073, 23.99306179, 30.68772458, 31.89431154,
       34.2022213 , 47.38815967, 49.70837744, 57.99367017, 59.95207004,
       64.6093734 , 67.31752023, 69.3533409 , 78.10984328, 79.52631413,
       80.3064658 , 83.97396141, 85.9983501 , 92.38132978, 96.21716624])