# Lab 01: Algorithm Design and Analysis
ISC 4221<br>
Due September 11th, 2019<br>
Connor Poetzinger<br> 

## 1. Selection Sort

Implementation of Selection Sort algorithm. This algorithm takes in an array of *n* real numbers to be sorted and outputs the the sorted array in ascending order as well as an index vector.

In [1]:
#Import modules 
import numpy as np
"""
Input: Numpy array of random real numbers from 0 to 100
Output: Sorted array and index vector

Goal: Take current element and swap it with the smallest element on its right 
"""

def selectionSort(A):
    #use numpy argsort to return indicies that would sort the array 
    indx = np.argsort(A)
    #Traverse through numpy array 
    for i in range(len(A)):
        #initial minimum location 
        min_loc = i
        #find location of smallest element on right 
        for j in range(i + 1, len(A)):
            #Check if number to the right is smaller then minimum location
            if A[j] < A[min_loc]:
                min_loc = j
        #Within the first for loop swap the minimum location with first element 
        A[min_loc], A[i] = A[i], A[min_loc]
    
    return A, indx

In [6]:
A = np.random.rand(25) * 100
A

array([43.68876071, 84.94889998, 14.75799518, 43.17786439, 40.37966961,
       44.83155606, 36.44750536, 35.71939085, 47.48190455, 87.23586669,
       66.97936385, 56.24355773, 75.66317062, 70.85055193, 24.64453212,
       85.49647876, 54.03985859, 87.61766933, 15.7937557 , 82.61693189,
       90.11162502, 42.93941659, 11.25919458, 25.57466831, 41.67145185])

In [7]:
selectionSort(A)

(array([11.25919458, 14.75799518, 15.7937557 , 24.64453212, 25.57466831,
        35.71939085, 36.44750536, 40.37966961, 41.67145185, 42.93941659,
        43.17786439, 43.68876071, 44.83155606, 47.48190455, 54.03985859,
        56.24355773, 66.97936385, 70.85055193, 75.66317062, 82.61693189,
        84.94889998, 85.49647876, 87.23586669, 87.61766933, 90.11162502]),
 array([22,  2, 18, 14, 23,  7,  6,  4, 24, 21,  3,  0,  5,  8, 16, 11, 10,
        13, 12, 19,  1, 15,  9, 17, 20], dtype=int32))

## 2. Bubble Sort

Implementation of Bubble Sort algorithm. This algorithm takes in an array of *n* real numbers to be sorted and outputs the the sorted array in ascending order as well as an index vector.

In [11]:
#Import modules 
import numpy as np
"""
Input: Numpy array of random real numbers from 0 to 100
Output: Sorted array and index vector

Goal: Move left to right, compare consedcutive elements and switch them if 
they are out of order. Continue until no swaps are made through an entire
sweep.
"""

def bubbleSort(A):
    #use numpy argsort to return indicies that would sort the array 
    indx = np.argsort(A)
    #Traverse the numpy array
    for i in range(len(A)):
        #At each sweep compare the current j with the next value 
        #Use length minus 1 since we are comparing the current value 
        #with the next 
        for j in range((len(A) - 1) - i):
            #Swap positions if element found is greater than the next 
            #element. Largest nums bubble to the back 
            if A[j] > A[j + 1]:
                #Current element moves to the back 
                A[j], A[j + 1] = A[j + 1], A[j]
    
    return A, indx

In [12]:
A = np.random.rand(25) * 100
A

array([27.86483988, 22.43284541, 22.82710413, 20.60534971, 51.10798082,
       67.35109439, 80.00961744,  2.03401364, 33.77106211, 63.51320345,
       51.14835546, 74.59618609, 75.53728165, 84.25138998, 16.63771714,
       77.83688885, 14.03892689, 57.59482158, 92.55267846,  5.41291683,
       41.37619183, 54.49078943, 38.51575659, 78.46253161, 48.82141606])

In [13]:
bubbleSort(A)

(array([ 2.03401364,  5.41291683, 14.03892689, 16.63771714, 20.60534971,
        22.43284541, 22.82710413, 27.86483988, 33.77106211, 38.51575659,
        41.37619183, 48.82141606, 51.10798082, 51.14835546, 54.49078943,
        57.59482158, 63.51320345, 67.35109439, 74.59618609, 75.53728165,
        77.83688885, 78.46253161, 80.00961744, 84.25138998, 92.55267846]),
 array([ 7, 19, 16, 14,  3,  1,  2,  0,  8, 22, 20, 24,  4, 10, 21, 17,  9,
         5, 11, 12, 15, 23,  6, 13, 18], dtype=int32))

## 3. A Basic Application of Sorting

Using the haversine algorithm, find the distance between the store distance and the user inputed longitude and latitude. 

In [27]:
import numpy as np 
import pandas as pd 

def haversin(data):
    
    """
    This function reads in user latitude and logitude to simulate logging customer
    call locations. The user's long and lat are then converted to radians along 
    with other pre-defined longs and lats imported from a text file and save to a 
    pandas dataframe. The function then computes the distance from the caller to 
    the the stores in the dataframe using the haversine formula. The distances are
    then sorted in ascending order and printed out to provide the customer with 
    a list of closest stores, and how many miles to the store. 
    """
    
    #Read in user long and lat 
    #must transform string values to float 
    lon1 = float(input("Enter longitude: "))
    lat1 = float(input("Enter latitude: "))
    
    #Radius of earth from the equator in miles (found on google)
    R = 3963.0
    
    #assign user lat and lon and datatable lat and long to variables
    #I use the in-built function map to assign the numpy function np.radians to the degree
    #lats and long to transform degree into radians 
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, data.latitude, data.longitude])
    
    #calculate the distance between the lats and longs
    lon_dist = lon2 - lon1
    lat_dist = lat2 - lat1
    
    #apply haversine formula 
    #np cos and sin provide for faster calculations 
    c = 2 * R * np.arcsin(np.sqrt((np.sin(lat_dist)/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin((lon_dist)/2)**2 ))
    
    #prompt user for the info provided 
    print("\nBelow are the closest stores from your location in ascending order")
    #apply selection sort
    sorted_result, indx = selectionSort(c)
    return c.tolist(), indx

   
#import data table 
#use pandas to assign columns using strings 
data = pd.read_table('stores_location.dat', delim_whitespace=True, names = ('store', 'city', 'latitude', 'N', 'longitude','W'))

#call function 
sorted_dist , indx = haversin(data)

#Sort the cities and stores based on the index from selectionSort(c)
sorted_cities = [data['city'][indx[i]] for i in range(len(data))]
sorted_stores = [data['store'][indx[i]] for i in range(len(data))]

#create a tuple to package store num, city, and dist together
test = list(zip(sorted_stores, sorted_cities, sort_dist))

#Create output dataframe
final_sort = pd.DataFrame(test, columns=['Store','City','Distance(m)'])
final_sort

Enter longitude: 82.1401
Enter latitude: 29.1872

Below are the closest stores from your location in ascending order


Store          City  Distance(m)
0  store#2   Gainesville    34.024058
1  store#6       Orlando    73.798287
2  store#4  Jacksonville    84.552802
3  store#5         Tampa    86.756136
4  store#1   Tallahassee   154.167562
5  store#7       Hialeah   256.349820
6  store#3         Miami   263.966405